---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.wego.weave.works
spec:
  group: wego.weave.works
  scope: Cluster
  names:
    kind: Application
    listKind: ApplicationList
    plural: apps
    singular: app
  versions:
    - name: v1alpha1
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["url", "path"]
              properties:
                url:
                  type: "string"
                  description: URL for the repo
                  minimum: 1
                  maximum: 1
                path:
                  type: "string"
                  description: Path to application manifests within the repo
                  minimum: 1
                  maximum: 1
          type: object
      served: true
      storage: true