{{- range .Values.applications }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: {{ .applicationName }}-bootstrap
  namespace: {{ $.Release.Namespace }}
spec:
  interval: 1m
  url: {{ .gitRepository }}
  ref:
    branch: {{ .branch | default "main" }}
  secretRef:
    name: {{ .applicationName }}-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .applicationName }}-secret
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  identity: {{ .privateKey }}
  known_hosts: {{ .knownHosts }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: {{ .applicationName }}-bootstrap
  namespace: {{ $.Release.Namespace }}
spec:
  interval: 1m
  path: {{ .path }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: {{ .applicationName }}-bootstrap
{{- end }}
...